name: Laravel CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel_test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    # Set up PHP and Node.js environments
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, bcmath
        coverage: none
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install PHP dependencies before modifying .env or running Laravel commands
    - name: Install PHP dependencies
      run: composer install --no-progress --no-interaction --prefer-dist

    # Install Node dependencies
    - name: Install Node dependencies
      run: npm ci

    # Configure .env for the testing environment after dependencies are installed
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Configure .env for Testing
      run: |
        echo "APP_ENV=testing" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel_test" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "SESSION_DRIVER=array" >> .env
        echo "CACHE_DRIVER=array" >> .env
        echo "QUEUE_CONNECTION=sync" >> .env
        echo "MAIL_MAILER=log" >> .env
        echo "VITE_DEV_SERVER=false" >> .env # Disable dev server for CI
        php artisan config:clear

    # Build Vite assets for Vue frontend
    - name: Build assets
      run: npm run build

    # Generate application key and set permissions
    - name: Generate application key
      run: php artisan key:generate

    - name: Set Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Run migrations on the MySQL test database
    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force

    # Run the test suite
    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan test
